### ISSUE TITLE
`:UpdateRemotePlugins` crashes Neovim

### ISSUE THREAD

**Issue by HiPhish** [adolenc/cl-neovim#10]
I followed all the steps of installation and when executing `:UpdateRemotePlugins` it crashed Neovim. I have Quicklisp installed to a non-standard location, `~/.local/share/quicklisp/setup.lisp`, so I set `let g:lisp_host_quicklisp_setup = '~/.local/share/quicklisp/setup.lisp'` in my `init.vim` right before `Plug 'adolenc/cl-neovim'`.

The first time I had tried it `:UpdateRemotePlugins` failed (as expected) because I hadn't set `g:lisp_host_quicklisp_setup`, so the error has to be somewhere after reading the `setup.lisp` file.

The crash displays:

```
Assertion failed: (!stream->closed), function wstream_write, file /tmp/neovim-20160912-2107-m91gva/src/nvim/event/wstream.c, line 74.
Abort trap: 6
```

Before the crash Neovim would appear to be hanging for a while, displaying only

```
remote/host: python3 host registered plugins ['deoplete', 'chromatica']
```

Executing Lisp expressions like `:Lisp (print (+ 2 3))` seems to work, so I don't know if something is missing. Running `:LispHostRunTests` doesn't print anything when it's done, so no idea what's going on there, it just opens a new (empty) file called `test.lisp_host_testa`. Here is my `rplugin.vim` file (after removing the testing part): http://pastebin.com/NUF8SZUt

**Comment by HiPhish** [comment]
Here is also the result of running `:CheckHealth lisp`:

```

health#lisp#check
================================================================================
## Lisp provider
  - INFO: Using default bindings ("sbcl") for g:lisp_host_prog.
  - INFO: Found SBCL version `SBCL 1.3.9' at `/usr/local/bin/sbcl'.
  - INFO: g:lisp_host_quicklisp_setup is bound to `~/.local/share/quicklisp/setup.lisp'.
  - INFO: Loading Quicklisp from `/Users/hiphish/.local/share/quicklisp/setup.lisp'.
  - INFO: Quicklisp is installed and gets properly loaded.
  - INFO: cl-neovim can be quickloaded.
  - SUCCESS: Lisp host should be working correctly!


```

**Comment by adolenc** [comment]
Hey, thanks for the detailed report!

So running `:UpdateRemotePlugins` definitely shouldn't crash your Neovim, but from everything else you posted it seems like the host should be functioning correctly (according to `rplugin.vim` it correctly reports the remote plugin specifications and running `:Lisp` confirms that it properly invokes the host).

I'm sorry for temporary inconvenience as I'll not be able to look into it in detail for a few more days. In the meantime, could I please ask you to check if you can get [the simple plugin from README](https://github.com/adolenc/cl-neovim#simple-plugin) to work? Calling `:UpdateRemotePlugins` might crash Neovim again, but if my current hypothesis is correct the specs in `rplugin.vim` should be properly populated and calling `:LispSampleCmd` should work.

And could you also please post your Neovim version (and if you didn't install by building it from source, how you installed it so I can reproduce this)?

**Comment by HiPhish** [comment]
The sample plugin prints `Command: Called 1 times, args: NIL, range: (1 1), bang: NIL` to my buffer, so that seems to work. My version is

```
NVIM v0.1.6-89-g2daf54e
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DE
CLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160912-2107-m91gva/build/config -I/tmp/neovim-20160912-2107-m91gva/src -I/tmp/neovim-20160912
-2107-m91gva/deps-build/usr/include -I/tmp/neovim-20160912-2107-m91gva/deps-build/usr/include -I/tmp/neovim-20160912-2107-m91gva/deps-bu
ild/usr/include -I/tmp/neovim-20160912-2107-m91gva/deps-build/usr/include -I/tmp/neovim-20160912-2107-m91gva/deps-build/usr/include -I/t
mp/neovim-20160912-2107-m91gva/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160
912-2107-m91gva/build/src/nvim/auto -I/tmp/neovim-20160912-2107-m91gva/build/include
Compiled by hiphish@My-iMac.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-2daf54e/share/nvim"
```

Installed from current `HEAD` via Homebrew package manager on OS X 10.11.6.

EDIT: Maybe this is relevant, when I run the command the first time in a Neovim session it takes several seconds for the output to appear, but after that it's instant. I guess it takes my Lisp environment that long to set everything up.

**Comment by adolenc** [comment]
Thanks, I'll go at it in a few days.

> I guess it takes my Lisp environment that long to set everything up

Yep, you are right. I haven't properly profiled this, but I would assume that Quicklisp adds quite a bit to that startup time. I simply decided that a few second hangup once per session is worth the convenience Quicklisp provides to the end user.

**Comment by justinmk** [comment]
Any crash in nvim is an nvim bug. If you can figure some reduced steps  that would help a lot.

**Comment by HiPhish** [comment]
Filed an issue over at Neovim: https://github.com/neovim/neovim/issues/5349

**Comment by HiPhish** [comment]
I can no longer reproduce this issue with Neovim version 0.3.0, running on Kubuntu 18.04. Closing the issue.
